# Generated by Django 5.0.3 on 2024-03-27 15:07

import django.db.models.deletion
import giftGenerator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=250)),
                ('untappd_url', models.URLField(validators=[giftGenerator.models.untappd_url_validator])),
                ('venue_website_url', models.URLField(validators=[giftGenerator.models.https_url_validator])),
            ],
        ),
        migrations.CreateModel(
            name='Beers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=250)),
                ('untappd_url', models.URLField(validators=[giftGenerator.models.untappd_url_validator])),
                ('venue_website_url', models.URLField(validators=[giftGenerator.models.https_url_validator])),
                ('abv', models.FloatField(default=0, null=True)),
                ('ibu', models.FloatField(default=0, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftGenerator.venues')),
            ],
        ),
    ]
