# Generated by Django 5.0.3 on 2024-03-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftGenerator', '0002_beers_brewery'),
    ]

    operations = [
        migrations.AddField(
            model_name='beers',
            name='rating',
            field=models.FloatField(default=0, null=True),
        ),
    ]
