# Generated by Django 5.0.3 on 2024-03-27 17:00

import giftGenerator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftGenerator', '0004_alter_beers_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beers',
            name='untappd_url',
            field=models.URLField(null=True, validators=[giftGenerator.models.untappd_url_validator]),
        ),
        migrations.AlterField(
            model_name='beers',
            name='venue_website_url',
            field=models.URLField(null=True, validators=[giftGenerator.models.https_url_validator]),
        ),
    ]
